library(testthat)
library(s4p)

source("dename.R")

#source("testthat/test_SpatialPolygridDataFrame_prepare.R")
## source("testthat/test_SpatialPolygridDataFrame_SpatialPolygridDataFrame.R")
## source("testthat/test_SpatialPolygridDataFrame_coerce.R")
## source("testthat/test_points2polygrid.R")
## source("testthat/test_polygrid2grid.R")
## source("testthat/test_SpatialPolygridDataFrame_coordinates_proj4string_bbox.R")
## source("testthat/test_SpatialPolygridDataFrame_subsetSDF.R")
## source("testthat/test_SpatialPolygridDataFrame_cbind.R")
## source("testthat/test_SpatialPolygridDataFrame_spplot.R")
## source("testthat/test_SpatialPolygridDataFrame_testData.R")
## source("testthat/test_testDataArtificial.R")
## source("testthat/test_subsetSDF.R")
## source("testthat/test_areaSDF.R")
## source("testthat/test_SpatialIndexDataFrame.R")
## source("testthat/test_SpatialDataFrame.R")
## source("testthat/test_testDataTelescopic.R")
### source("testthat/test_spplotLog.R") # does only make sense 'by hand'
#source("testthat/test_Simulations.R")
#source("testthat/test_cbindSimulations.R")
#source("testthat/test_extractSpatialDataFrame.R")
#source("testthat/test_SDF2simulations.R")
#source("testthat/test_loadSimulations.R")
#source("testthat/test_changeSimulationsPath.R")
#source("testthat/test_copySimulations.R")
#source("testthat/test_radioactivePlumes.R")
#source("testthat/test_summaryPlumes.R")
#source("testthat/test_summaryLocations.R")
# source("testthat/subset.simulations.R")
# source("testthat/test_replaceDefault.R") # to be updated if all types have been defined  
#source("testthat/test_simulationsApply.R") # don't run like this (old extra code, files generated...)
#source("testthat/test_interpolation.R") # don't run (generates files, takes long)
#source("testthat/test_measurementResult.R") # does not test 'measurementResult' but the derived functions
#source("testthat/test_costFunctions.R") # turns all pre-costFunctions into those that can be used in optimisation (functions may need improvement for harmonisation)
#source("testthat/test_optimiseSD_greedy.R") 
#source("testthat/test_optimiseSD_ssa.R") 
#source("testthat/test_optimiseSD_genetic.R") 
#source("testthat/test_optimiseSD_global.R") 
#source("testthat/test_optimiseSD_manual.R") # interactive, not to be run automatically
#source("testthat/test_interpol0reg.R") 